#!/bin/sh
set -efu
ma=$(dpkg-architecture -qDEB_HOST_MULTIARCH)
blaslib=$(update-alternatives --list libblas.so.3-$ma | grep -m1 $(basename $0))
update-alternatives --set libblas.so.3-$ma $blaslib

echo "=== testing "$(basename $0)" ==="

# one python is enough
PYS=${PYS:-"$(py3versions -d 2>/dev/null)"}

#test only modules that link against libblas
PYS=$PYS TESTPKG=odr debian/tests/python3
PYS=$PYS TESTPKG=optimize debian/tests/python3
PYS=$PYS TESTPKG=spatial debian/tests/python3
PYS=$PYS TESTPKG=special debian/tests/python3
PYS=$PYS TESTPKG=cluster debian/tests/python3
PYS=$PYS TESTPKG=integrate debian/tests/python3
PYS=$PYS TESTPKG=interpolate debian/tests/python3
PYS=$PYS TESTPKG=sparse debian/tests/python3
PYS=$PYS TESTPKG=linalg debian/tests/python3
